version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run dev
    depends_on:
      - supabase
    restart: unless-stopped

  # Supabase local development
  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "54321:54321" # Supabase Studio
      - "54322:54322" # Supabase API
    environment:
      - POSTGRES_PASSWORD=postgres
      - SUPABASE_AUTH_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=admin
    volumes:
      - ./supabase/migrations:/supabase/migrations
      - ./supabase/functions:/supabase/functions
    restart: unless-stopped 